name: Sprint Review
on:
  workflow_dispatch:
jobs:
  release-pull-request:
    name: ReleaseAction
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: peterjgrainger/action-create-branch@v2.0.1
      name: create release-candidate branch from default branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: "release-candidate" 
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      name: configure git
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: rebase release-candidate to master
      run: |
        git fetch
        git checkout release-candidate
        git rebase -X theirs origin/master
        git push --force-with-lease origin release-candidate 
    - name: pull-request-action
      id: cpr
      uses: vsoch/pull-request-action@1.0.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "master"
        PULL_REQUEST_TITLE:  "Release PR"
        PULL_REQUEST_FROM_BRANCH: "release-candidate"
